name: Check

on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - '**'

jobs:
  check:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          cache: 'npm'
          node-version: ${{ matrix.node-version }}

      - name: Install deps
        run: npm ci

      - name: Commit linting
        uses: wagoid/commitlint-github-action@v2

      - name: Code linting
        run: npm run lint:check
        env:
          CI: true

      - name: Dependency check
        run: npm run depcheck

      - name: Check typings
        run: npm run check:types
