# On each new commit to master, create/update a PR with release
# automatically bumps version and creates changelog as per conventional commits
name: Release

on:
  push:
    branches:
      - master

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: GoogleCloudPlatform/release-please-action@v3
        id: release
        with:
          token: ${{ secrets.GHA_PAT_BASIC }}
          release-type: node
          package-name: bee-desktop
          draft: true
      - name: Trigger assets builds on release
        if: steps.release.outputs.release_created == 'true'
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.GHA_PAT_BASIC }}
          event-type: assets-build
